idf_component_register(
    SRCS
        "generated/animations.c"
        "generated/setup_scr_dashboard.c"
        "generated/setup_ui.c"
        "generated/images/LOGO_bordered_260x60.c"
        "generated/images/about_188x54.c"
        "generated/images/about_b_188x54.c"
        "generated/images/back_22x22.c"
        "generated/images/connect_126x36.c"
        "generated/images/control_188x54.c"
        "generated/images/control_b_188x54.c"
        "generated/images/dash_a_212x66.c"
        "generated/images/dash_c_212x66.c"
        "generated/images/dash_c2_212x66.c"
        "generated/images/detect_188x54.c"
        "generated/images/detect_b_188x54.c"
        "generated/images/disconnect_126x36.c"
        "generated/images/display_188x54.c"
        "generated/images/display_b_188x54.c"
        "generated/images/log_a_212x66.c"
        "generated/images/logc_212x66.c"
        "generated/images/logc1_212x66.c"
        "generated/images/net_188x54.c"
        "generated/images/net_b_188x54.c"
        "generated/images/next_22x22.c"
        "generated/images/set_a_212x66.c"
        "generated/images/setc_212x66.c"
        "generated/images/setc1_212x66.c"
        "generated/images/sys_a_212x66.c"
        "generated/images/sysc_212x66.c"
        "generated/images/sysc1_212x66.c"
        "generated/fonts/lv_font_MiSansVF_12_12.c"
        "generated/fonts/lv_font_MiSansVF_14_14.c"
        "generated/fonts/lv_font_MiSansVF_16_16.c"
        "generated/fonts/lv_font_MiSansVF_24_24.c"
        "generated/fonts/lv_font_MiSans_Heavy_16_16.c"
        "generated/fonts/lv_font_MiSans_Heavy_24_24.c"
        "generated/fonts/lv_font_Misans_Heavy_14_14.c"
        "sdk/cmd.c"
        "sdk/evt.c"
        "sdk/scr_list.c"
        "sdk/ui.c"
        "simulator/dummy.c"
    INCLUDE_DIRS
        "generated"
        "generated/images"
        "generated/fonts"
        "sdk"
    REQUIRES
        lvgl
        Ethernet_app
)
