#pragma once

/*
 * Sorter debug hardware map.
 *
 * Keep unknown pins at -1. The BSP treats -1 as disabled/virtual where the
 * underlying ESP-IDF driver supports it, so the first debug build will not
 * drive unverified hardware accidentally.
 */

#define SORTER_MOTOR_COUNT 3
#define SORTER_MOTOR1_PWM_A_GPIO 32
#define SORTER_MOTOR1_PWM_B_GPIO 36
#define SORTER_MOTOR0_PWM_A_GPIO 2
#define SORTER_MOTOR0_PWM_B_GPIO 3
#define SORTER_MOTOR2_PWM_A_GPIO 4
#define SORTER_MOTOR2_PWM_B_GPIO 5

#define SORTER_MOTOR0_REVERSE 0
#define SORTER_MOTOR1_REVERSE 0
#define SORTER_MOTOR2_REVERSE 0

#define SORTER_DEFAULT_MOTOR_A_SPEED_PERCENT 65
#define SORTER_DEFAULT_MOTOR_B_SPEED_PERCENT 100
#define SORTER_DEFAULT_MOTOR_C_SPEED_PERCENT 100

#define SORTER_DEFAULT_HANDOFF_DELAY_MS 100
#define SORTER_DEFAULT_BELT_A_TIMEOUT_MS 4500
#define SORTER_DEFAULT_BELT_B_TIMEOUT_MS 900
#define SORTER_DEFAULT_BELT_C_TIMEOUT_MS 1300
#define SORTER_DEFAULT_LOST_TIMEOUT_MIN_MS 3000
#define SORTER_DEFAULT_LOST_TIMEOUT_MAX_MS 6000

#define SORTER_SENSOR_S1_GPIO 22
#define SORTER_SENSOR_S2_GPIO 23
#define SORTER_SENSOR_S3_GPIO -1
#define SORTER_SENSOR_S4_GPIO -1

#define SORTER_SENSOR_S1_ACTIVE_LEVEL 1
#define SORTER_SENSOR_S2_ACTIVE_LEVEL 1
#define SORTER_SENSOR_S3_ACTIVE_LEVEL 1
#define SORTER_SENSOR_S4_ACTIVE_LEVEL 1

#define SORTER_ENCODER_COUNT 3
#define SORTER_ENCODER0_GPIO_A -1
#define SORTER_ENCODER0_GPIO_B -1
#define SORTER_ENCODER1_GPIO_A -1
#define SORTER_ENCODER1_GPIO_B -1
#define SORTER_ENCODER2_GPIO_A -1
#define SORTER_ENCODER2_GPIO_B -1

#define SORTER_ENCODER0_REVERSE 0
#define SORTER_ENCODER1_REVERSE 0
#define SORTER_ENCODER2_REVERSE 0

#define SORTER_ENCODER_PHASE_PULSES_PER_REV 12
#define SORTER_ENCODER_SAMPLE_PERIOD_MS 100
#define SORTER_ENCODER_WHEEL_DIAMETER_MM 76
#define SORTER_ENCODER_GLITCH_FILTER_NS 1000
