#pragma once

/*
 * Sorter debug hardware map.
 *
 * Keep unknown pins at -1. The BSP treats -1 as disabled/virtual where the
 * underlying ESP-IDF driver supports it, so the first debug build will not
 * drive unverified hardware accidentally.
 */

#define SORTER_DEBUG_ENABLE_USB_SERIAL 1

#define SORTER_MOTOR_COUNT 3
#define SORTER_MOTOR0_PWM_A_GPIO -1
#define SORTER_MOTOR0_PWM_B_GPIO -1
#define SORTER_MOTOR1_PWM_A_GPIO -1
#define SORTER_MOTOR1_PWM_B_GPIO -1
#define SORTER_MOTOR2_PWM_A_GPIO -1
#define SORTER_MOTOR2_PWM_B_GPIO -1

#define SORTER_MOTOR0_REVERSE 0
#define SORTER_MOTOR1_REVERSE 0
#define SORTER_MOTOR2_REVERSE 0

#define SORTER_SENSOR_S1_GPIO CONFIG_SORT_SENSOR_S1_GPIO
#define SORTER_SENSOR_S2_GPIO CONFIG_SORT_SENSOR_S2_GPIO
#define SORTER_SENSOR_S3_GPIO CONFIG_SORT_SENSOR_S3_GPIO
#define SORTER_SENSOR_S4_GPIO CONFIG_SORT_SENSOR_S4_GPIO

#define SORTER_SENSOR_S1_ACTIVE_LEVEL 1
#define SORTER_SENSOR_S2_ACTIVE_LEVEL 1
#define SORTER_SENSOR_S3_ACTIVE_LEVEL 1
#define SORTER_SENSOR_S4_ACTIVE_LEVEL 1

#define SORTER_ENCODER_COUNT 3
#define SORTER_ENCODER0_GPIO_A 5
#define SORTER_ENCODER0_GPIO_B 6
#define SORTER_ENCODER1_GPIO_A -1
#define SORTER_ENCODER1_GPIO_B -1
#define SORTER_ENCODER2_GPIO_A -1
#define SORTER_ENCODER2_GPIO_B -1

#define SORTER_ENCODER0_REVERSE 0
#define SORTER_ENCODER1_REVERSE 0
#define SORTER_ENCODER2_REVERSE 0

#define SORTER_ENCODER_PHASE_PULSES_PER_REV 12
#define SORTER_ENCODER_SAMPLE_PERIOD_MS 100
#define SORTER_ENCODER_WHEEL_DIAMETER_MM 76
#define SORTER_ENCODER_GLITCH_FILTER_NS 1000
